### ISSUE TITLE
line too long in prng_class.f90

### ISSUE THREAD

**Issue by Beliavsky** [leonfoks/coretran#16]
There is a line that is too long in prng_class.f90:

c:\fortran\public_domain\coretran>gfortran -c prng_class.f90
prng_class.f90:167:132:

   generic, public :: rngExponential => rngExponential_d1_Prng_, rngExponential_d1D_Prng_, rngExponential_d2D_Prng_, rngExponential_d3D_Prng_
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
prng_class.f90:167:38:

   generic, public :: rngExponential => rngExponential_d1_Prng_, rngExponential_d1D_Prng_, rngExponential_d2D_Prng_, rngExponential_d3D_Prng_
                                      1
Error: Undefined specific binding 'rngexponential_d' as target of GENERIC 'rngexponential' at (1)
f951.exe: some warnings being treated as errors

**Comment by leonfoks** [comment]
This is avoidable using the compiler flag -ffree-line-length-none.
If you use my CMake approach to create the make files, it should work.
