### ISSUE TITLE
line too long in Stopwatch_Class.f90

### ISSUE THREAD

**Issue by Beliavsky** [leonfoks/coretran#17]
c:\fortran\public_domain\coretran>gfortran -c Stopwatch_Class.f90
Stopwatch_Class.f90:219:132:

     res = trim(str(this%StopTime_(5)))//':'//trim(str(this%StopTime_(6)))//':'//trim(str(this%StopTime_(7)))//'.'//trim(str(this%StopTime_(8)))
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
Stopwatch_Class.f90:219:132:

     res = trim(str(this%StopTime_(5)))//':'//trim(str(this%StopTime_(6)))//':'//trim(str(this%StopTime_(7)))//'.'//trim(str(this%StopTime_(8)))
                                                                                                                                    1
Error: 'sto' at (1) is not a member of the 'stopwatch' structure
f951.exe: some warnings being treated as errors

**Comment by leonfoks** [comment]
This is avoidable using the compiler flag -ffree-line-length-none.
If you use my CMake approach to create the make files, it should work.
