### ISSUE TITLE
lines too long in m_tests.f90

### ISSUE THREAD

**Issue by Beliavsky** [leonfoks/coretran#18]
I am using GNU Fortran (GCC) 8.0.1 20180408 (experimental) on Windows 10. 

c:\fortran\public_domain\coretran>gfortran -c m_tests.f90
m_tests.f90:424:132:

   call test%test(all(da%i%values(1:3) == [30, 20, 10]) .and. all(da%v%values(1:3) == [30.d0, 20.d0, 10.d0]), 'dArgDynamicArray%prepend')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:424:110:

   call test%test(all(da%i%values(1:3) == [30, 20, 10]) .and. all(da%v%values(1:3) == [30.d0, 20.d0, 10.d0]), 'dArgDynamicArray%prepend')
                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:426:132:

   call test%test(all(da%i%values(1:4) == [30, 20, 10, 40]) .and. all(da%v%values(1:4) == [30.d0, 20.d0, 10.d0, 40.d0]), 'dArgDynamicArray%append')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:426:121:

   call test%test(all(da%i%values(1:4) == [30, 20, 10, 40]) .and. all(da%v%values(1:4) == [30.d0, 20.d0, 10.d0, 40.d0]), 'dArgDynamicArray%append')
                                                                                                                         1
Error: Unterminated character constant beginning at (1)
m_tests.f90:428:132:

   call test%test(all(da%i%values(1:3) == [30, 10, 40]) .and. all(da%v%values(1:3) == [30.d0, 10.d0, 40.d0]), 'dArgDynamicArray%remove')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:428:110:

   call test%test(all(da%i%values(1:3) == [30, 10, 40]) .and. all(da%v%values(1:3) == [30.d0, 10.d0, 40.d0]), 'dArgDynamicArray%remove')
                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:443:132:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:443:103:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSorted')
                                                                                                       1
Error: Unterminated character constant beginning at (1)
m_tests.f90:449:132:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:449:103:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                       1
Error: Unterminated character constant beginning at (1)
m_tests.f90:451:132:

   call test%test(all(da%i%values(1:4)==[3, 4, 1, 2]) .and. all(da%v%values(1:4)==[10.d0, 15.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:451:113:

   call test%test(all(da%i%values(1:4)==[3, 4, 1, 2]) .and. all(da%v%values(1:4)==[10.d0, 15.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                                 1
Error: Unterminated character constant beginning at (1)
m_tests.f90:459:132:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:459:103:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSorted')
                                                                                                       1
Error: Unterminated character constant beginning at (1)
m_tests.f90:465:132:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:465:103:

   call test%test(all(da%i%values(1:3)==[3, 1, 2]) .and. all(da%v%values(1:3)==[10.d0, 20.d0, 30.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                       1
Error: Unterminated character constant beginning at (1)
m_tests.f90:467:132:

   call test%test(all(da%i%values(1:3)==[3, 4, 1]) .and. all(da%v%values(1:3)==[10.d0, 15.d0, 20.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:467:103:

   call test%test(all(da%i%values(1:3)==[3, 4, 1]) .and. all(da%v%values(1:3)==[10.d0, 15.d0, 20.d0]), 'dArgDynamicArray%insertSortedUnique')
                                                                                                       1
Error: Unterminated character constant beginning at (1)
m_tests.f90:497:132:

   call test%test(all(ida%i%values(1:4) == [30, 20, 10, 40]) .and. all(ida%v%values(1:4) == [30, 20, 10, 40]), 'iArgDynamicArray%append')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:497:111:

   call test%test(all(ida%i%values(1:4) == [30, 20, 10, 40]) .and. all(ida%v%values(1:4) == [30, 20, 10, 40]), 'iArgDynamicArray%append')
                                                                                                               1
Error: Unterminated character constant beginning at (1)
m_tests.f90:520:132:

   call test%test(all(ida%i%values(1:3)==[3, 1, 2]) .and. all(ida%v%values(1:3)==[10, 20, 30]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:520:132:

   call test%test(all(ida%i%values(1:3)==[3, 1, 2]) .and. all(ida%v%values(1:3)==[10, 20, 30]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Syntax error in argument list at (1)
m_tests.f90:522:132:

   call test%test(all(ida%i%values(1:4)==[3, 4, 1, 2]) .and. all(ida%v%values(1:4)==[10, 15, 20, 30]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:522:103:

   call test%test(all(ida%i%values(1:4)==[3, 4, 1, 2]) .and. all(ida%v%values(1:4)==[10, 15, 20, 30]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                       1
Error: Unterminated character constant beginning at (1)
m_tests.f90:536:132:

   call test%test(all(ida%i%values(1:3)==[3, 1, 2]) .and. all(ida%v%values(1:3)==[10, 20, 30]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:536:132:

   call test%test(all(ida%i%values(1:3)==[3, 1, 2]) .and. all(ida%v%values(1:3)==[10, 20, 30]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Syntax error in argument list at (1)
m_tests.f90:538:132:

   call test%test(all(ida%i%values(1:3)==[3, 4, 1]) .and. all(ida%v%values(1:3)==[10, 15, 20]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:538:132:

   call test%test(all(ida%i%values(1:3)==[3, 4, 1]) .and. all(ida%v%values(1:3)==[10, 15, 20]), 'iArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Syntax error in argument list at (1)
m_tests.f90:564:132:

   call test%test(all(idda%i%values(1:2) == [20_i64, 10_i64]) .and. all(idda%v%values(1:2) == [20_i64, 10_i64]), 'idArgDynamicArray%insert')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:564:113:

   call test%test(all(idda%i%values(1:2) == [20_i64, 10_i64]) .and. all(idda%v%values(1:2) == [20_i64, 10_i64]), 'idArgDynamicArray%insert')
                                                                                                                 1
Error: Unterminated character constant beginning at (1)
m_tests.f90:566:132:

   call test%test(all(idda%i%values(1:3) == [30_i64, 20_i64, 10_i64]) .and. all(idda%v%values(1:3) == [30_i64, 20_i64, 10_i64]), 'idArgDynamicArray%prepend')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:566:129:

   call test%test(all(idda%i%values(1:3) == [30_i64, 20_i64, 10_i64]) .and. all(idda%v%values(1:3) == [30_i64, 20_i64, 10_i64]), 'idArgDynamicArray%prepend')
                                                                                                                                 1
Error: Unterminated character constant beginning at (1)
m_tests.f90:568:132:

   call test%test(all(idda%i%values(1:4) == [30_i64, 20_i64, 10_i64, 40_i64]) .and. all(idda%v%values(1:4) == [30_i64, 20_i64, 10_i64, 40_i64]), 'idArgDynamicArray%append')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:568:132:

   call test%test(all(idda%i%values(1:4) == [30_i64, 20_i64, 10_i64, 40_i64]) .and. all(idda%v%values(1:4) == [30_i64, 20_i64, 10_i64, 40_i64]), 'idArgDynamicArray%append')
                                                                                                                                    1
Error: Syntax error in array constructor at (1)
m_tests.f90:570:132:

   call test%test(all(idda%i%values(1:3) == [30_i64, 10_i64, 40_i64]) .and. all(idda%v%values(1:3) == [30_i64, 10_i64, 40_i64]), 'idArgDynamicArray%remove')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:570:129:

   call test%test(all(idda%i%values(1:3) == [30_i64, 10_i64, 40_i64]) .and. all(idda%v%values(1:3) == [30_i64, 10_i64, 40_i64]), 'idArgDynamicArray%remove')
                                                                                                                                 1
Error: Unterminated character constant beginning at (1)
m_tests.f90:585:132:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:585:110:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSorted')
                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:591:132:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:591:110:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:593:132:

   call test%test(all(idda%i%values(1:4)==[3, 4, 1, 2]) .and. all(idda%v%values(1:4)==[10_i64, 15_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:593:121:

   call test%test(all(idda%i%values(1:4)==[3, 4, 1, 2]) .and. all(idda%v%values(1:4)==[10_i64, 15_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                                         1
Error: Unterminated character constant beginning at (1)
m_tests.f90:601:132:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:601:110:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSorted')
                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:607:132:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:607:110:

   call test%test(all(idda%i%values(1:3)==[3, 1, 2]) .and. all(idda%v%values(1:3)==[10_i64, 20_i64, 30_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:609:132:

   call test%test(all(idda%i%values(1:3)==[3, 4, 1]) .and. all(idda%v%values(1:3)==[10_i64, 15_i64, 20_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:609:110:

   call test%test(all(idda%i%values(1:3)==[3, 4, 1]) .and. all(idda%v%values(1:3)==[10_i64, 15_i64, 20_i64]), 'idArgDynamicArray%insertSortedUnique')
                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:637:132:

   call test%test(all(rda%i%values(1:3) == [30, 20, 10]) .and. all(rda%v%values(1:3) == [30.0, 20.0, 10.0]), 'rArgDynamicArray%prepend')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:637:109:

   call test%test(all(rda%i%values(1:3) == [30, 20, 10]) .and. all(rda%v%values(1:3) == [30.0, 20.0, 10.0]), 'rArgDynamicArray%prepend')
                                                                                                             1
Error: Unterminated character constant beginning at (1)
m_tests.f90:639:132:

   call test%test(all(rda%i%values(1:4) == [30, 20, 10, 40]) .and. all(rda%v%values(1:4) == [30.0, 20.0, 10.0, 40.0]), 'rArgDynamicArray%append')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:639:119:

   call test%test(all(rda%i%values(1:4) == [30, 20, 10, 40]) .and. all(rda%v%values(1:4) == [30.0, 20.0, 10.0, 40.0]), 'rArgDynamicArray%append')
                                                                                                                       1
Error: Unterminated character constant beginning at (1)
m_tests.f90:641:132:

   call test%test(all(rda%i%values(1:3) == [30, 10, 40]) .and. all(rda%v%values(1:3) == [30.0, 10.0, 40.0]), 'rArgDynamicArray%remove')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:641:109:

   call test%test(all(rda%i%values(1:3) == [30, 10, 40]) .and. all(rda%v%values(1:3) == [30.0, 10.0, 40.0]), 'rArgDynamicArray%remove')
                                                                                                             1
Error: Unterminated character constant beginning at (1)
m_tests.f90:656:132:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:656:132:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Syntax error in argument list at (1)
m_tests.f90:662:132:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:662:102:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:664:132:

   call test%test(all(rda%i%values(1:4)==[3, 4, 1, 2]) .and. all(rda%v%values(1:4)==[10.0, 15.0, 20.0, 30.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:664:111:

   call test%test(all(rda%i%values(1:4)==[3, 4, 1, 2]) .and. all(rda%v%values(1:4)==[10.0, 15.0, 20.0, 30.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                               1
Error: Unterminated character constant beginning at (1)
m_tests.f90:672:132:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:672:132:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSorted')
                                                                                                                                    1
Error: Syntax error in argument list at (1)
m_tests.f90:678:132:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:678:102:

   call test%test(all(rda%i%values(1:3)==[3, 1, 2]) .and. all(rda%v%values(1:3)==[10.0, 20.0, 30.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:680:132:

   call test%test(all(rda%i%values(1:3)==[3, 4, 1]) .and. all(rda%v%values(1:3)==[10.0, 15.0, 20.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:680:102:

   call test%test(all(rda%i%values(1:3)==[3, 4, 1]) .and. all(rda%v%values(1:3)==[10.0, 15.0, 20.0]), 'rArgDynamicArray%insertSortedUnique')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1039:132:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - sqrt(c1D(ia1D(1:10)))) <= 1.d-15), '2D - KdTreeSearch%kNearest, k nearest')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1039:112:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - sqrt(c1D(ia1D(1:10)))) <= 1.d-15), '2D - KdTreeSearch%kNearest, k nearest')
                                                                                                                1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1048:132:

   call test%test(all(da%i%values == ia1D(1:15)) .and. all(abs(da%v%values - (c1D(1:15))) <= 1.d-15), '2D - KdTreeSearch%kNearest, radius search')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1048:102:

   call test%test(all(da%i%values == ia1D(1:15)) .and. all(abs(da%v%values - (c1D(1:15))) <= 1.d-15), '2D - KdTreeSearch%kNearest, radius search')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1052:132:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - (c1D(1:10))) <= 1.d-15), '2D - KdTreeSearch%kNearest, k radius search')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1052:102:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - (c1D(1:10))) <= 1.d-15), '2D - KdTreeSearch%kNearest, k radius search')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1093:132:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - sqrt(d1D(ia1D(1:10)))) <= 1.d-15), '3D - KdTreeSearch%kNearest')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1093:112:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - sqrt(d1D(ia1D(1:10)))) <= 1.d-15), '3D - KdTreeSearch%kNearest')
                                                                                                                1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1101:132:

   call test%test(all(da%i%values == ia1D(1:15)) .and. all(abs(da%v%values - (d1D(1:15))) <= 1.d-15), '3D - KdTreeSearch%kNearest, radius search')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1101:102:

   call test%test(all(da%i%values == ia1D(1:15)) .and. all(abs(da%v%values - (d1D(1:15))) <= 1.d-15), '3D - KdTreeSearch%kNearest, radius search')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1105:132:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - (d1D(1:10))) <= 1.d-15), '3D - KdTreeSearch%kNearest, k radius search')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1105:102:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - (d1D(1:10))) <= 1.d-15), '3D - KdTreeSearch%kNearest, k radius search')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1149:132:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - sqrt(c1D(ia1D(1:10)))) <= 1.d-15), 'KD - KdTreeSearch%kNearest')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1149:112:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - sqrt(c1D(ia1D(1:10)))) <= 1.d-15), 'KD - KdTreeSearch%kNearest')
                                                                                                                1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1159:132:

   call test%test(all(da%i%values == ia1D(1:15)) .and. all(abs(da%v%values - (d1D(1:15))) <= 1.d-15), 'KD - KdTreeSearch%kNearest, radius search')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1159:102:

   call test%test(all(da%i%values == ia1D(1:15)) .and. all(abs(da%v%values - (d1D(1:15))) <= 1.d-15), 'KD - KdTreeSearch%kNearest, radius search')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1163:132:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - (d1D(1:10))) <= 1.d-15), 'KD - KdTreeSearch%kNearest, k radius search')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1163:102:

   call test%test(all(da%i%values == ia1D(1:10)) .and. all(abs(da%v%values - (d1D(1:10))) <= 1.d-15), 'KD - KdTreeSearch%kNearest, k radius search')
                                                                                                      1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1535:132:

   call test%test(all(shape(a3D) == [20,20,20]) .and. all(a3D(1:10,1:10,1:10) == 3.d0) .and. all(a3D(11:20,11:20,11:20) == 0.d0),'reallocate_d3D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1535:129:

   call test%test(all(shape(a3D) == [20,20,20]) .and. all(a3D(1:10,1:10,1:10) == 3.d0) .and. all(a3D(11:20,11:20,11:20) == 0.d0),'reallocate_d3D')
                                                                                                                                 1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1550:132:

   call test%test(all(shape(ia3D) == [20,20,20]) .and. all(ia3d(1:10,1:10,1:10) == 3) .and. all(ia3D(11:20,11:20,11:20) == 0),'reallocate_i3D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1550:126:

   call test%test(all(shape(ia3D) == [20,20,20]) .and. all(ia3d(1:10,1:10,1:10) == 3) .and. all(ia3D(11:20,11:20,11:20) == 0),'reallocate_i3D')
                                                                                                                              1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1565:132:

   call test%test(all(shape(iad3D) == [20,20,20]) .and. all(iad3d(1:10,1:10,1:10) == 3)  .and. all(iad3D(11:20,11:20,11:20) == 0),'reallocate_id3D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1565:130:

   call test%test(all(shape(iad3D) == [20,20,20]) .and. all(iad3d(1:10,1:10,1:10) == 3)  .and. all(iad3D(11:20,11:20,11:20) == 0),'reallocate_id3D')
                                                                                                                                  1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1575:132:

   call test%test(all(shape(z2D) == [20,20]) .and. all(z2D(1:10,1:10) == (2.d0, 0.d0)) .and. all(z2D(11:20,11:20) == (0.d0, 0.d0)),'reallocate_c2D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1575:131:

   call test%test(all(shape(z2D) == [20,20]) .and. all(z2D(1:10,1:10) == (2.d0, 0.d0)) .and. all(z2D(11:20,11:20) == (0.d0, 0.d0)),'reallocate_c2D')
                                                                                                                                   1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1580:132:

   call test%test(all(shape(z3D) == [20,20,20]) .and. all(z3D(1:10,1:10,1:10) == (3.d0, 0.d0)) .and. all(z3D(11:20,11:20,11:20) == (0.d0, 0.d0)),'reallocate_c3D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1580:132:

   call test%test(all(shape(z3D) == [20,20,20]) .and. all(z3D(1:10,1:10,1:10) == (3.d0, 0.d0)) .and. all(z3D(11:20,11:20,11:20) == (0.d0, 0.d0)),'reallocate_c3D')
                                                                                                                                    1
Error: Expected a right parenthesis in expression at (1)
m_tests.f90:1590:132:

   call test%test(all(shape(zz2D) == [20,20]) .and. all(zz2D(1:10,1:10) == (2.d0, 0.d0)) .and. all(zz2D(11:20,11:20) == (0.d0, 0.d0)),'reallocate_z2D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1590:132:

   call test%test(all(shape(zz2D) == [20,20]) .and. all(zz2D(1:10,1:10) == (2.d0, 0.d0)) .and. all(zz2D(11:20,11:20) == (0.d0, 0.d0)),'reallocate_z2D')
                                                                                                                                    1
Error: Syntax error in argument list at (1)
m_tests.f90:1595:132:

   call test%test(all(shape(zz3D) == [20,20,20]) .and. all(zz3D(1:10,1:10,1:10) == (3.d0, 0.d0)) .and. all(zz3D(11:20,11:20,11:20) == (0.d0, 0.d0)),'reallocate_z3D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1595:132:

   call test%test(all(shape(zz3D) == [20,20,20]) .and. all(zz3D(1:10,1:10,1:10) == (3.d0, 0.d0)) .and. all(zz3D(11:20,11:20,11:20) == (0.d0, 0.d0)),'reallocate_z3D')
                                                                                                                                    1
Error: Syntax error in expression at (1)
m_tests.f90:1605:132:

   call test%test(all(shape(la2D) == [20,20]) .and. all(la2D(1:10,1:10) .eqv. .true.) .and. all(la2D(11:20,11:20) .eqv. .false.),'reallocate_l2D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1605:129:

   call test%test(all(shape(la2D) == [20,20]) .and. all(la2D(1:10,1:10) .eqv. .true.) .and. all(la2D(11:20,11:20) .eqv. .false.),'reallocate_l2D')
                                                                                                                                 1
Error: Unterminated character constant beginning at (1)
m_tests.f90:1610:132:

   call test%test(all(shape(la3D) == [20,20,20]) .and. all(la3D(1:10,1:10,1:10) .eqv. .true.) .and. all(la3D(11:20,11:20,11:20) .eqv. .false.),'reallocate_l3D')
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
m_tests.f90:1610:132:

   call test%test(all(shape(la3D) == [20,20,20]) .and. all(la3D(1:10,1:10,1:10) .eqv. .true.) .and. all(la3D(11:20,11:20,11:20) .eqv. .false.),'reallocate_l3D')
                                                                                                                                    1
Error: Syntax error in expression at (1)
f951.exe: some warnings being treated as errors

**Comment by leonfoks** [comment]
This is avoidable using the compiler flag -ffree-line-length-none.
If you use my CMake approach to create the make files, it should work.
