### ISSUE TITLE
compile failed on GNU Fortran (GCC) 7.3.1 (Red Hat 7.3.1-5)

### ISSUE THREAD

**Issue by rmcd-mscb** [leonfoks/coretran#20]
Compile failed as follows: 

rmcd@localhost build]$ make
[  1%] Building Fortran object CMakeFiles/coretran.dir/core/m_variableKind.f90.o
[  2%] Building Fortran object CMakeFiles/coretran.dir/core/m_errors.f90.o
[  4%] Building Fortran object CMakeFiles/coretran.dir/core/m_unitTester.f90.o
[  5%] Building Fortran object CMakeFiles/coretran.dir/core/m_allocate.f90.o
/home/rmcd/git/coretran/src/core/m_allocate.f90:44.4:

    module subroutine allocate_r1D(this, n)
    1
Error: Unclassifiable statement at (1)
/home/rmcd/git/coretran/src/core/m_allocate.f90:47.11:

      real(r32), allocatable, intent(inout) :: this(:) 
           1
Error: Parameter 'r32' at (1) has not been declared or is a variable, which does not reduce to a constant expression
/home/rmcd/git/coretran/src/core/m_allocate.f90:49.14:

      integer(i32), intent(in) :: n 
              1
Error: Parameter 'i32' at (1) has not been declared or is a variable, which does not reduce to a constant expression
/home/rmcd/git/coretran/src/core/m_allocate.f90:51.7:

    end subroutine
       1
Error: Expecting END INTERFACE statement at (1)

**Comment by rmcd-mscb** [comment]
configured with:
cmake -DCMAKE_BUILD_TYPE=DEBUG --DCMAKE_INTALL_PREFIX=/usr/local -G"Unix Makefiles" ../src

**Comment by rmcd-mscb** [comment]
cmake was using an unexpected version of gfortran.  I used the -DCMAKE_Fortran_COMPILER option with success.

**Comment by leonfoks** [comment]
Thanks for the issue, I've updated the docs to explain why this option is important.
