### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by mdpiper** [leonfoks/coretran#22]
This is a request to `git tag` a release of coretran.

**Comment by mdpiper** [comment]
Some context: @rmcd-mscb and I are working to wrap @pnorton-usgs's PRMS6 with a [Basic Model Interface](https://bmi.readthedocs.io/en/latest/) and make it callable in Python through [pymt](https://pymt.readthedocs.io/en/latest/). At @csdms, we use [Anaconda](https://www.anaconda.com/distribution/) as our distribution tool. I'd like to make a conda package for coretran. This makes it super easy for users (and developers!) to install. While I could build off a commit, it's easier in conda to build off a release.

**Comment by leonfoks** [comment]
Yeah this would be awesome.  I thought CMAKE was super easy to install, but I bet it's even easier with Anaconda.  Do you know if it cleverly handles submodules and hierarchy dependency of the newer style of Fortran like CMAKE? i.e. only re-compiles changed submodules and links rather than doing a full recompile?

**Comment by leonfoks** [comment]
My KdTree does not currently use the adaptive arithmetic in-sphere/in-circle geometry code yet, let me update those routines and then I can do a tag on a release.

**Comment by mdpiper** [comment]
@leonfoks Thank you for your help with this!

The neat thing about a conda package is that it uses the developer's build process. I'll include a build script that simply calls your cmake setup (which worked flawlessly on the first try on my Linux machine). You can then build, through conda, binaries for the package on macOS, Linux, and Windows. For example, [here's](https://github.com/csdms-stack/fastmech-recipe) my recipe for the FaSTEMCH model, and [here's](https://anaconda.org/csdms-stack/fastmech) the associated Anaconda page where the binaries are hosted.

I'll stay tuned for updates on this issue. Thanks again!

**Comment by mdpiper** [comment]
@leonfoks Hi Leon -- I just wanted to check in to see if you'd be willing to stamp a release on coretran. For my own use, I've been [building it](https://github.com/csdms-stack/coretran-recipe) with conda on Linux and macOS, and I'm planning to try soon on Windows.

**Comment by leonfoks** [comment]
@mdpiper Done!

**Comment by mdpiper** [comment]
@leonfoks Thank you!
