### ISSUE TITLE
ProgressBar seems nonfunctional

### ISSUE THREAD

**Issue by mostlyharmlessone** [leonfoks/coretran#30]
In  module ProgressBar_Class, public :: set is commented out, as well as the subsequent lines.  
As a result, the sample code provided  at the head of ProgressBar_Class.f90 fails on the line call P%set(N, time = .false.) because "set’ at (1) is not a member of the ‘progressbar’ structure".  

Is there a modification to the sample code envisioned, or is this dead code?  

Uncommenting the codes leads to compile errors: set_i1_progressbar’ and ‘set_id1_progressbar’ for GENERIC ‘set’ at (1) are ambiguous  and set_i1_progressbar’ must be a module procedure or an external procedure with an explicit interface at (1) etc.

**Comment by leonfoks** [comment]
Its been a long time since I worked on this repo tbh.  But ive changed those lines in the docs and removed the commented generics too.  Go ahead and try again and let me know

**Comment by mostlyharmlessone** [comment]
Seems to work, thanksA de BeusOn Mar 20, 2024, at 17:03, Leon Foks ***@***.***> wrote:﻿
Its been a long time since I worked on this repo tbh.  But ive changed those lines in the docs and removed the commented generics too.  Go ahead and try again and let me know
