### ISSUE TITLE
dynamicArrays folder missing CMakeLists.txt

### ISSUE THREAD

**Issue by ybursim** [leonfoks/coretran#7]
The CMakeLists.txt file appears to be missing from dynamicArrays folder. I created the file with the content below, and it compiled. Please advise if this is not the correct content.

target_sources(${libName}
    PUBLIC
        "${CMAKE_CURRENT_LIST_DIR}/m_dynamicArray.f90"
        "${CMAKE_CURRENT_LIST_DIR}/m_fixedArray.f90"
        "${CMAKE_CURRENT_LIST_DIR}/sm_dDynamicArray.f90"
        "${CMAKE_CURRENT_LIST_DIR}/sm_iDynamicArray.f90"
        "${CMAKE_CURRENT_LIST_DIR}/sm_idDynamicArray.f90"
        "${CMAKE_CURRENT_LIST_DIR}/sm_rDynamicArray.f90"
)

**Comment by leonfoks** [comment]
Thanks for the heads up...it was in my ignore file for some reason....
Fixed.
