### ISSUE TITLE
replace 'call system' with 'call execute_command_line'

### ISSUE THREAD

**Issue by ybursim** [leonfoks/coretran#8]
Leon, in order to compile the progress bar feature with a GNU 2008 standard (using Simply Fortran v 2.40)  it was necessary for me to replace the intrinsic SYSTEM with EXECUTE_COMMAND_LINE.

**Comment by leonfoks** [comment]
@ybursim Where did you replace "system" with "execute_command_line"?  I have not used system calls in coretran.

**Comment by ybursim** [comment]
In my copy of Banner_Class.f90 lines 55, 113, and 117.
